sudo: required

language: node_js

node_js: 4

services:
  - docker

before_install:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t gtrabanco/ghost:0.9.0-armhf 0.9.0-armhf

after_success:
  - docker run gtrabanco/ghost:0.9.0-armhf
  - docker push gtrabanco/ghost:0.9.0-armhf