sudo: required

language: node_js

node_js: 4

services:
  - docker

before_install:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t gtrabanco/ghost:0.9.0-armhf 0.9.0-armhf

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push gtrabanco/ghost:0.9.0-armhf;
      fi
  - docker run gtrabanco/ghost:0.9.0-armhf /bin/sh -c "cd /root; bundle exec rake test"

script:
- bundle exec rake test